version: '3.9'
services:
  db:
    container_name: db-container
    image: postgres:${POSTGRES_VERSION}
    platform: linux/amd64
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ='Asia/Tokyo'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data

